lookahead_distance : 0.20 # Forward looking distance
speed : 0.10  # Maximum speed
expansion_size : 2  # Wall expansion coefficient
target_error : 0.05  # Margin of error to target
robot_r : 0.50  # Robot distance for local security
