lookahead_distance : 3.5  # Forward looking distance
speed : 0.18  # Maximum speed
expansion_size : 3  # Wall expansion coefficient
target_error : 0.15  # Margin of error to target
robot_r : 0.05  # Robot distance for local security
