lookahead_distance : 0.10  # Forward looking distance
speed : 0.10  # Maximum speed
expansion_size : 3  # Wall expansion coefficient
target_error : 0.15  # Margin of error to target
robot_r : 0.30  # Robot distance for local security
